// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf39sHJ8lJCzwl7dFgEs9hwswRHtADRP4',
    appId: '1:164617498397:web:6a9ff3b655086913eabbf4',
    messagingSenderId: '164617498397',
    projectId: 'eventtiming-71bac',
    authDomain: 'eventtiming-71bac.firebaseapp.com',
    storageBucket: 'eventtiming-71bac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzuRA8nQlIltuZ8ijRgg-NINREV6xoK34',
    appId: '1:164617498397:android:f27c1d8318632880eabbf4',
    messagingSenderId: '164617498397',
    projectId: 'eventtiming-71bac',
    storageBucket: 'eventtiming-71bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzK8zSEBN_zsN8cPge_MZd9UTLBq9ngE',
    appId: '1:164617498397:ios:39f431476441bb37eabbf4',
    messagingSenderId: '164617498397',
    projectId: 'eventtiming-71bac',
    storageBucket: 'eventtiming-71bac.firebasestorage.app',
    iosClientId: '164617498397-0mbpvlrfeqrrmv56mur3p8kqs1p25j4b.apps.googleusercontent.com',
    iosBundleId: 'com.eventtiming.eventTiming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGzK8zSEBN_zsN8cPge_MZd9UTLBq9ngE',
    appId: '1:164617498397:ios:39f431476441bb37eabbf4',
    messagingSenderId: '164617498397',
    projectId: 'eventtiming-71bac',
    storageBucket: 'eventtiming-71bac.firebasestorage.app',
    iosClientId: '164617498397-0mbpvlrfeqrrmv56mur3p8kqs1p25j4b.apps.googleusercontent.com',
    iosBundleId: 'com.eventtiming.eventTiming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf39sHJ8lJCzwl7dFgEs9hwswRHtADRP4',
    appId: '1:164617498397:web:83a354d2a64016f5eabbf4',
    messagingSenderId: '164617498397',
    projectId: 'eventtiming-71bac',
    authDomain: 'eventtiming-71bac.firebaseapp.com',
    storageBucket: 'eventtiming-71bac.firebasestorage.app',
  );
}
